runtime: python27
api_version: 1
threadsafe: true

instance_class: F1

handlers:
- url: /api/last_build_result/.*
  script: webapi.app

- url: /dashboard/
  login: required
  script: dashboard.app
- url: /dashboard/(.*)
  login: required
  script: dashboard.app

- url: /static/(.*)
  static_files: static/\1
  upload: static/.*

includes:
- plugin/line/app.yaml
- plugin/twilio/app.yaml
- plugin/render_text/app.yaml

libraries:
- name: ssl
  version: latest
- name: PIL
  version: "1.1.7"

