runtime: python27
api_version: 1
threadsafe: true

instance_class: F2

handlers:
- url: /line/callback/.*
  script: linecallback.app
- url: /line/api/.*
  script: linecallback.app
- url: /line/image/.*
  script: image.app
- url: /twilio/callback/.*
  script: linecallback.app
- url: /twilio/dial_content/.*
  script: linecallback.app
- url: /twilio/dial_completed_callback/.*
  script: linecallback.app
- url: /twilio/internal_callback/.*
  script: linecallback.app

libraries:
- name: ssl
  version: latest
- name: PIL
  version: "1.1.7"

