runtime: python27
api_version: 1
threadsafe: true

instance_class: F2

handlers:
- url: /line/callback/.*
  script: linecallback.app
- url: /line/image/.*
  script: image.app

libraries:
- name: ssl
  version: latest
- name: PIL
  version: "1.1.7"

